// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: frame.proto

package com.cryptoregistry.protos;

public final class Frame {
  private Frame() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AuthenticatedStringProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AuthenticatedStringProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string encoding = 1;</code>
     *
     * <pre>
     *for example, "UTF-8"
     * </pre>
     */
    boolean hasEncoding();
    /**
     * <code>required string encoding = 1;</code>
     *
     * <pre>
     *for example, "UTF-8"
     * </pre>
     */
    java.lang.String getEncoding();
    /**
     * <code>required string encoding = 1;</code>
     *
     * <pre>
     *for example, "UTF-8"
     * </pre>
     */
    com.google.protobuf.ByteString
        getEncodingBytes();

    /**
     * <code>required bytes data = 2;</code>
     */
    boolean hasData();
    /**
     * <code>required bytes data = 2;</code>
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>required bytes hmac = 3;</code>
     */
    boolean hasHmac();
    /**
     * <code>required bytes hmac = 3;</code>
     */
    com.google.protobuf.ByteString getHmac();
  }
  /**
   * Protobuf type {@code AuthenticatedStringProto}
   */
  public static final class AuthenticatedStringProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:AuthenticatedStringProto)
      AuthenticatedStringProtoOrBuilder {
    // Use AuthenticatedStringProto.newBuilder() to construct.
    private AuthenticatedStringProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AuthenticatedStringProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AuthenticatedStringProto defaultInstance;
    public static AuthenticatedStringProto getDefaultInstance() {
      return defaultInstance;
    }

    public AuthenticatedStringProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AuthenticatedStringProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              encoding_ = bs;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              data_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              hmac_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cryptoregistry.protos.Frame.internal_static_AuthenticatedStringProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cryptoregistry.protos.Frame.internal_static_AuthenticatedStringProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cryptoregistry.protos.Frame.AuthenticatedStringProto.class, com.cryptoregistry.protos.Frame.AuthenticatedStringProto.Builder.class);
    }

    public static com.google.protobuf.Parser<AuthenticatedStringProto> PARSER =
        new com.google.protobuf.AbstractParser<AuthenticatedStringProto>() {
      public AuthenticatedStringProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AuthenticatedStringProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AuthenticatedStringProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ENCODING_FIELD_NUMBER = 1;
    private java.lang.Object encoding_;
    /**
     * <code>required string encoding = 1;</code>
     *
     * <pre>
     *for example, "UTF-8"
     * </pre>
     */
    public boolean hasEncoding() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string encoding = 1;</code>
     *
     * <pre>
     *for example, "UTF-8"
     * </pre>
     */
    public java.lang.String getEncoding() {
      java.lang.Object ref = encoding_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          encoding_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string encoding = 1;</code>
     *
     * <pre>
     *for example, "UTF-8"
     * </pre>
     */
    public com.google.protobuf.ByteString
        getEncodingBytes() {
      java.lang.Object ref = encoding_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        encoding_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>required bytes data = 2;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int HMAC_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString hmac_;
    /**
     * <code>required bytes hmac = 3;</code>
     */
    public boolean hasHmac() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes hmac = 3;</code>
     */
    public com.google.protobuf.ByteString getHmac() {
      return hmac_;
    }

    private void initFields() {
      encoding_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
      hmac_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasEncoding()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHmac()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getEncodingBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, data_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, hmac_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getEncodingBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, hmac_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cryptoregistry.protos.Frame.AuthenticatedStringProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cryptoregistry.protos.Frame.AuthenticatedStringProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cryptoregistry.protos.Frame.AuthenticatedStringProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cryptoregistry.protos.Frame.AuthenticatedStringProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cryptoregistry.protos.Frame.AuthenticatedStringProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cryptoregistry.protos.Frame.AuthenticatedStringProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cryptoregistry.protos.Frame.AuthenticatedStringProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cryptoregistry.protos.Frame.AuthenticatedStringProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cryptoregistry.protos.Frame.AuthenticatedStringProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cryptoregistry.protos.Frame.AuthenticatedStringProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cryptoregistry.protos.Frame.AuthenticatedStringProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AuthenticatedStringProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AuthenticatedStringProto)
        com.cryptoregistry.protos.Frame.AuthenticatedStringProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cryptoregistry.protos.Frame.internal_static_AuthenticatedStringProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cryptoregistry.protos.Frame.internal_static_AuthenticatedStringProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cryptoregistry.protos.Frame.AuthenticatedStringProto.class, com.cryptoregistry.protos.Frame.AuthenticatedStringProto.Builder.class);
      }

      // Construct using com.cryptoregistry.protos.Frame.AuthenticatedStringProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        encoding_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        hmac_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cryptoregistry.protos.Frame.internal_static_AuthenticatedStringProto_descriptor;
      }

      public com.cryptoregistry.protos.Frame.AuthenticatedStringProto getDefaultInstanceForType() {
        return com.cryptoregistry.protos.Frame.AuthenticatedStringProto.getDefaultInstance();
      }

      public com.cryptoregistry.protos.Frame.AuthenticatedStringProto build() {
        com.cryptoregistry.protos.Frame.AuthenticatedStringProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cryptoregistry.protos.Frame.AuthenticatedStringProto buildPartial() {
        com.cryptoregistry.protos.Frame.AuthenticatedStringProto result = new com.cryptoregistry.protos.Frame.AuthenticatedStringProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.encoding_ = encoding_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.hmac_ = hmac_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cryptoregistry.protos.Frame.AuthenticatedStringProto) {
          return mergeFrom((com.cryptoregistry.protos.Frame.AuthenticatedStringProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cryptoregistry.protos.Frame.AuthenticatedStringProto other) {
        if (other == com.cryptoregistry.protos.Frame.AuthenticatedStringProto.getDefaultInstance()) return this;
        if (other.hasEncoding()) {
          bitField0_ |= 0x00000001;
          encoding_ = other.encoding_;
          onChanged();
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasHmac()) {
          setHmac(other.getHmac());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasEncoding()) {
          
          return false;
        }
        if (!hasData()) {
          
          return false;
        }
        if (!hasHmac()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cryptoregistry.protos.Frame.AuthenticatedStringProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cryptoregistry.protos.Frame.AuthenticatedStringProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object encoding_ = "";
      /**
       * <code>required string encoding = 1;</code>
       *
       * <pre>
       *for example, "UTF-8"
       * </pre>
       */
      public boolean hasEncoding() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string encoding = 1;</code>
       *
       * <pre>
       *for example, "UTF-8"
       * </pre>
       */
      public java.lang.String getEncoding() {
        java.lang.Object ref = encoding_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            encoding_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string encoding = 1;</code>
       *
       * <pre>
       *for example, "UTF-8"
       * </pre>
       */
      public com.google.protobuf.ByteString
          getEncodingBytes() {
        java.lang.Object ref = encoding_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          encoding_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string encoding = 1;</code>
       *
       * <pre>
       *for example, "UTF-8"
       * </pre>
       */
      public Builder setEncoding(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        encoding_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string encoding = 1;</code>
       *
       * <pre>
       *for example, "UTF-8"
       * </pre>
       */
      public Builder clearEncoding() {
        bitField0_ = (bitField0_ & ~0x00000001);
        encoding_ = getDefaultInstance().getEncoding();
        onChanged();
        return this;
      }
      /**
       * <code>required string encoding = 1;</code>
       *
       * <pre>
       *for example, "UTF-8"
       * </pre>
       */
      public Builder setEncodingBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        encoding_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes data = 2;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes data = 2;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>required bytes data = 2;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes data = 2;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString hmac_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes hmac = 3;</code>
       */
      public boolean hasHmac() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes hmac = 3;</code>
       */
      public com.google.protobuf.ByteString getHmac() {
        return hmac_;
      }
      /**
       * <code>required bytes hmac = 3;</code>
       */
      public Builder setHmac(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        hmac_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes hmac = 3;</code>
       */
      public Builder clearHmac() {
        bitField0_ = (bitField0_ & ~0x00000004);
        hmac_ = getDefaultInstance().getHmac();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AuthenticatedStringProto)
    }

    static {
      defaultInstance = new AuthenticatedStringProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:AuthenticatedStringProto)
  }

  public interface StringProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:StringProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string encoding = 1;</code>
     *
     * <pre>
     *for example, "UTF-8"
     * </pre>
     */
    boolean hasEncoding();
    /**
     * <code>required string encoding = 1;</code>
     *
     * <pre>
     *for example, "UTF-8"
     * </pre>
     */
    java.lang.String getEncoding();
    /**
     * <code>required string encoding = 1;</code>
     *
     * <pre>
     *for example, "UTF-8"
     * </pre>
     */
    com.google.protobuf.ByteString
        getEncodingBytes();

    /**
     * <code>required bytes data = 2;</code>
     */
    boolean hasData();
    /**
     * <code>required bytes data = 2;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code StringProto}
   */
  public static final class StringProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:StringProto)
      StringProtoOrBuilder {
    // Use StringProto.newBuilder() to construct.
    private StringProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StringProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StringProto defaultInstance;
    public static StringProto getDefaultInstance() {
      return defaultInstance;
    }

    public StringProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StringProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              encoding_ = bs;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cryptoregistry.protos.Frame.internal_static_StringProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cryptoregistry.protos.Frame.internal_static_StringProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cryptoregistry.protos.Frame.StringProto.class, com.cryptoregistry.protos.Frame.StringProto.Builder.class);
    }

    public static com.google.protobuf.Parser<StringProto> PARSER =
        new com.google.protobuf.AbstractParser<StringProto>() {
      public StringProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StringProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StringProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ENCODING_FIELD_NUMBER = 1;
    private java.lang.Object encoding_;
    /**
     * <code>required string encoding = 1;</code>
     *
     * <pre>
     *for example, "UTF-8"
     * </pre>
     */
    public boolean hasEncoding() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string encoding = 1;</code>
     *
     * <pre>
     *for example, "UTF-8"
     * </pre>
     */
    public java.lang.String getEncoding() {
      java.lang.Object ref = encoding_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          encoding_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string encoding = 1;</code>
     *
     * <pre>
     *for example, "UTF-8"
     * </pre>
     */
    public com.google.protobuf.ByteString
        getEncodingBytes() {
      java.lang.Object ref = encoding_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        encoding_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>required bytes data = 2;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private void initFields() {
      encoding_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasEncoding()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getEncodingBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getEncodingBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cryptoregistry.protos.Frame.StringProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cryptoregistry.protos.Frame.StringProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cryptoregistry.protos.Frame.StringProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cryptoregistry.protos.Frame.StringProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cryptoregistry.protos.Frame.StringProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cryptoregistry.protos.Frame.StringProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cryptoregistry.protos.Frame.StringProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cryptoregistry.protos.Frame.StringProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cryptoregistry.protos.Frame.StringProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cryptoregistry.protos.Frame.StringProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cryptoregistry.protos.Frame.StringProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code StringProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:StringProto)
        com.cryptoregistry.protos.Frame.StringProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cryptoregistry.protos.Frame.internal_static_StringProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cryptoregistry.protos.Frame.internal_static_StringProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cryptoregistry.protos.Frame.StringProto.class, com.cryptoregistry.protos.Frame.StringProto.Builder.class);
      }

      // Construct using com.cryptoregistry.protos.Frame.StringProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        encoding_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cryptoregistry.protos.Frame.internal_static_StringProto_descriptor;
      }

      public com.cryptoregistry.protos.Frame.StringProto getDefaultInstanceForType() {
        return com.cryptoregistry.protos.Frame.StringProto.getDefaultInstance();
      }

      public com.cryptoregistry.protos.Frame.StringProto build() {
        com.cryptoregistry.protos.Frame.StringProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cryptoregistry.protos.Frame.StringProto buildPartial() {
        com.cryptoregistry.protos.Frame.StringProto result = new com.cryptoregistry.protos.Frame.StringProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.encoding_ = encoding_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cryptoregistry.protos.Frame.StringProto) {
          return mergeFrom((com.cryptoregistry.protos.Frame.StringProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cryptoregistry.protos.Frame.StringProto other) {
        if (other == com.cryptoregistry.protos.Frame.StringProto.getDefaultInstance()) return this;
        if (other.hasEncoding()) {
          bitField0_ |= 0x00000001;
          encoding_ = other.encoding_;
          onChanged();
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasEncoding()) {
          
          return false;
        }
        if (!hasData()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cryptoregistry.protos.Frame.StringProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cryptoregistry.protos.Frame.StringProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object encoding_ = "";
      /**
       * <code>required string encoding = 1;</code>
       *
       * <pre>
       *for example, "UTF-8"
       * </pre>
       */
      public boolean hasEncoding() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string encoding = 1;</code>
       *
       * <pre>
       *for example, "UTF-8"
       * </pre>
       */
      public java.lang.String getEncoding() {
        java.lang.Object ref = encoding_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            encoding_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string encoding = 1;</code>
       *
       * <pre>
       *for example, "UTF-8"
       * </pre>
       */
      public com.google.protobuf.ByteString
          getEncodingBytes() {
        java.lang.Object ref = encoding_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          encoding_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string encoding = 1;</code>
       *
       * <pre>
       *for example, "UTF-8"
       * </pre>
       */
      public Builder setEncoding(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        encoding_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string encoding = 1;</code>
       *
       * <pre>
       *for example, "UTF-8"
       * </pre>
       */
      public Builder clearEncoding() {
        bitField0_ = (bitField0_ & ~0x00000001);
        encoding_ = getDefaultInstance().getEncoding();
        onChanged();
        return this;
      }
      /**
       * <code>required string encoding = 1;</code>
       *
       * <pre>
       *for example, "UTF-8"
       * </pre>
       */
      public Builder setEncodingBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        encoding_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes data = 2;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes data = 2;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>required bytes data = 2;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes data = 2;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:StringProto)
    }

    static {
      defaultInstance = new StringProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:StringProto)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthenticatedStringProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AuthenticatedStringProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StringProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_StringProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013frame.proto\"H\n\030AuthenticatedStringProt" +
      "o\022\020\n\010encoding\030\001 \002(\t\022\014\n\004data\030\002 \002(\014\022\014\n\004hma" +
      "c\030\003 \002(\014\"-\n\013StringProto\022\020\n\010encoding\030\001 \002(\t" +
      "\022\014\n\004data\030\002 \002(\014B$\n\031com.cryptoregistry.pro" +
      "tos\200\001\000\210\001\000\220\001\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AuthenticatedStringProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AuthenticatedStringProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AuthenticatedStringProto_descriptor,
        new java.lang.String[] { "Encoding", "Data", "Hmac", });
    internal_static_StringProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_StringProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_StringProto_descriptor,
        new java.lang.String[] { "Encoding", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
